### ISSUE TITLE
Package name was changed on PyPI to pytest-check

### ISSUE THREAD

**Issue by anjos** [conda-forge/pytest_check-feedstock#3]
### Solution to issue cannot be found in the documentation.

- [X] I checked the documentation.

### Issue

The name of this package has changed from `pytest_check` to `pytest-check`.  The PyPI links would not work anymore.

It would be good if this feedstock could catch-up.

### Installed packages

```shell
Not relevant
```

### Environment info

```shell
Not relevant
```

**Comment by anjos** [comment]
@thewchan: what I meant is that this feedstock should probably be renamed as `pytest-check-feedstock` to match the PyPI package name change.

**Comment by thewchan** [comment]
@conda-forge/core see above, not sure what the protocol is? I feel like in the past we might have just left it

**Comment by beckermr** [comment]
We cannot rename feedstocks. The options are:

1. We can and should add outputs to the current feedstock (e.g. both pytest_check and pytest-check).
2. A new feedstock can be submitted to staged recipes. We'll need to map old outputs to the new one in the feedstock-outputs repo.

**Comment by thewchan** [comment]
@beckermr how do we do option 1?

**Comment by beckermr** [comment]
See the conda-build documentation on the outputs section in the yaml.

**Comment by anjos** [comment]
Is there a migration path to solution 2?  Some sort of deprecation?

**Comment by beckermr** [comment]
I mean sure. We can submit the recipe we have as-is to staged-recipes and make a new feedstock. We can then adjust conda-forge's metadata to allow uploads from the new feedstock. However, unless we abandon users who have been using `pytest_check` in their own recipes/environments, we will always have to keep the `pytest_check` package around.

Once a name is shipped, we can't unship it.

**Comment by anjos** [comment]
It is acceptable to leave the existing packages installable.  I'm curious, however, if a migration workflow **for users** exists.  For example, through an installation warning in case the package name is changed.

**Comment by anjos** [comment]
Or a redirection.

**Comment by beckermr** [comment]
We do not have a migration workflow for users. Conda can issue warnings but not redirect in useful ways without simply carrying the extra output name around.

**Comment by anjos** [comment]
This package is now shipped as `pytest-check` instead of `pytest_check`.  Versions 1.1.2 and above follow the new pattern due to commit https://github.com/conda-forge/pytest_check-feedstock/pull/2/commits/00296eb0195761a8f05c0ed9d6ea8cbb6d69cb8b#

What should we do?

**Comment by beckermr** [comment]
Use the outputs feature of conda build to make packages with both names. Consult the conda build docs for how to specify this in the meta.yaml.

**Comment by anjos** [comment]
OK, will see how to go about this.

**Comment by anjos** [comment]
@beckermr: I have one remaining question - can we just rename this repo to `pytest-check-feedstock`, to match the official package name, or not?
